# Generated by Django 3.0.6 on 2020-05-07 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_commercial', models.BooleanField(default=False, verbose_name='Коммерческая')),
                ('is_residential', models.BooleanField(default=False, verbose_name='Жилая')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, help_text='Без пробелов, скобок, +7 и 8. <b style="color:red;font-size:10px;">ТОЛЬКО ЦИФРЫ !!!</b><br>Пример: 9131112233', max_length=20, null=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=user_profile.models.generate_url_for_user_image, verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
