# Generated by Django 3.0.6 on 2020-05-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.ManyToManyField(blank=True, default=None, related_name='profile_specialization', to='user_profile.Specialization', verbose_name='Специализация'),
        ),
    ]
