# Generated by Django 3.0.6 on 2020-05-07 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_auto_20200507_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=user_profile.models.generate_url_for_user_image, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_commercia',
            field=models.BooleanField(default=False, verbose_name='Коммерческая'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_residential',
            field=models.BooleanField(default=False, verbose_name='Жилая'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
