# Generated by Django 3.0.6 on 2020-05-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200507_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_commercial',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_residential',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
