# Generated by Django 3.0.6 on 2020-05-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователя'},
        ),
        migrations.AddField(
            model_name='specialization',
            name='short_name',
            field=models.CharField(default=None, max_length=10, unique=True, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Формат: YYYY-MM-DD', null=True, verbose_name='День рождения'),
        ),
    ]
