# Generated by Django 3.0.6 on 2020-05-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200508_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='text', help_text='Без пробелов, скобок, +7 и 8. <b style="color:red;font-size:10px;">ТОЛЬКО ЦИФРЫ !!!</b><br>Пример: 9131112233', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
