# Generated by Django 3.0.6 on 2020-05-07 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_auto_20200507_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Без пробелов, скобок, +7 и 8. <p style="color:red;font-size:18px;">ТОЛЬКО ЦИФРЫ !!!</p>', max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
