# Generated by Django 3.0.6 on 2020-05-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'VK'), ('twitter', 'Twitter')], max_length=25, verbose_name='Социальная сеть'),
        ),
    ]
