# Generated by Django 3.0.6 on 2020-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200507_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(blank=True, choices=[('whatsapp', 'Whatsapp'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('vk', 'VK'), ('twitter', 'Twitter')], max_length=25, verbose_name='Социальная сеть'),
        ),
    ]
