# Generated by Django 3.0.6 on 2020-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberofrooms',
            name='additional_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Добавочное название'),
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='is_active_load_data',
            field=models.BooleanField(default=False, help_text='Отключит данные о квартирах, занесенные вручную.', verbose_name='Включить загруженные данные'),
        ),
        migrations.AlterField(
            model_name='numberofrooms',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Название'),
        ),
    ]
