# Generated by Django 3.0.6 on 2020-05-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialcomplex',
            name='number_of_storeys',
            field=models.IntegerField(blank=True, db_index=True, help_text='ОСТАВИТЬ ПУСТЫМ! Если в ЖК несколько строений', null=True, verbose_name='Этажность'),
        ),
    ]
