# Generated by Django 3.0.6 on 2020-05-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0002_auto_20200507_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoresidentialcomplex',
            name='description',
        ),
        migrations.AddField(
            model_name='videoresidentialcomplex',
            name='add_text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Доплнительный текст'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='is_active_load_data',
            field=models.BooleanField(default=False, help_text='Отключит данные о квартирах, занесенные вручную.', verbose_name='Включить загруженные данные о квартирах'),
        ),
    ]
