# Generated by Django 3.0.6 on 2020-05-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0002_auto_20200508_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberofrooms',
            options={'ordering': ['id'], 'verbose_name': 'Количество комнат', 'verbose_name_plural': 'Количество комнат'},
        ),
    ]
