# Generated by Django 3.0.6 on 2020-05-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0003_auto_20200508_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplansresidentialpremise',
            name='residential_premises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplans_residential_complex', to='residential_properties.ResidentialPremise', verbose_name='Жилое помещение'),
        ),
        migrations.AlterField(
            model_name='imagesresidentialcomplex',
            name='residential_complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_residential_complex', to='residential_properties.ResidentialComplex', verbose_name='Жилой Комплекс'),
        ),
    ]
