# Generated by Django 3.0.6 on 2020-05-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0005_auto_20200509_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorplansresidentialpremise',
            name='residential_premises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_residential_premises', to='residential_properties.ResidentialPremise', verbose_name='Жилое помещение'),
        ),
    ]
