# Generated by Django 3.0.6 on 2020-05-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0006_auto_20200509_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='url_name',
            field=models.CharField(blank=True, default='wert', help_text='Для адресной строки в браузере. Только ЛАТИНИИЦА!!! Без: / и пробелов.', max_length=255, null=True, verbose_name='URL для этого ЖК'),
        ),
    ]
