# Generated by Django 3.0.6 on 2020-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0008_auto_20200511_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialcomplex',
            name='main_image_thumb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thumbnail image'),
        ),
    ]
