# Generated by Django 3.0.6 on 2020-05-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0009_residentialcomplex_main_image_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentialcomplex',
            options={'ordering': ['id'], 'verbose_name': 'Жилой Комплекс', 'verbose_name_plural': 'Жилые Комплексы'},
        ),
        migrations.AddField(
            model_name='imagesresidentialcomplex',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thumbnail image'),
        ),
    ]
