# Generated by Django 3.0.6 on 2020-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0008_auto_20200518_1843'),
        ('residential_properties', '0010_auto_20200516_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentialcomplex',
            name='address',
        ),
        migrations.AddField(
            model_name='residentialcomplex',
            name='address',
            field=models.ManyToManyField(blank=True, default=None, related_name='rescomplex_address', to='geo_location.Address', verbose_name='Адрес'),
        ),
    ]
