# Generated by Django 3.0.6 on 2020-05-19 17:39

from django.db import migrations, models
import residential_properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('residential_properties', '0012_auto_20200520_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesresidentialcomplex',
            name='image',
            field=models.FileField(blank=True, help_text='После сохранения автоматически меняет высоту картинки на 500px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=residential_properties.models.generate_url_for_image, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagesresidentialcomplex',
            name='image_thumb',
            field=models.FileField(blank=True, help_text='МОЖНО НЕ ЗАПОЛНЯТЬ, генирируеться автоматически из "Главное изображение ЖК" с высотой картинки 300px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=residential_properties.models.generate_url_for_image, verbose_name='Thumbnail image'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='main_image',
            field=models.FileField(blank=True, help_text='После сохранения автоматически меняет высоту картинки на 500px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=residential_properties.models.generate_url_for_image, verbose_name='Главное изображение ЖК'),
        ),
        migrations.AlterField(
            model_name='residentialcomplex',
            name='main_image_thumb',
            field=models.FileField(blank=True, help_text='МОЖНО НЕ ЗАПОЛНЯТЬ, генирируеться автоматически из "Главное изображение ЖК" с высотой картинки 300px.<br>Соотношение сторон сохраняеться.', null=True, upload_to=residential_properties.models.generate_url_for_image, verbose_name='Thumbnail image'),
        ),
    ]
