# Generated by Django 3.0.6 on 2020-05-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocommercialpremises',
            name='description',
        ),
        migrations.AddField(
            model_name='videocommercialpremises',
            name='add_text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Доплнительный текст'),
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='address',
            field=models.CharField(default=None, max_length=150, verbose_name='Адрес'),
        ),
    ]
