# Generated by Django 3.0.6 on 2020-05-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0002_auto_20200508_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialpremises',
            name='cost_of_sale',
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='max_cost_of_sale',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоймость на продажу, до'),
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='min_cost_of_sale',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоймость на продажу, от'),
        ),
    ]
