# Generated by Django 3.0.6 on 2020-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0006_auto_20200509_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialpremises',
            name='cooker_hood',
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='cooker_hood',
            field=models.ManyToManyField(blank=True, default=None, related_name='compremises_cookerhood', to='commercial_properties.CookerHood', verbose_name='Вытяжка'),
        ),
    ]
