# Generated by Django 3.0.6 on 2020-05-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0007_auto_20200510_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscategory',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='alt_attr',
            field=models.CharField(blank=True, default='text', max_length=300, verbose_name='img alt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communicationsystems',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cookerhood',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floorplanscommercialpremises',
            name='alt_attr',
            field=models.CharField(blank=True, default='text', max_length=300, verbose_name='img alt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagescommercialpremises',
            name='alt_attr',
            field=models.CharField(blank=True, default='text', max_length=300, verbose_name='img alt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purposeofcommercialpremise',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relativelocation',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typeentrancetocommercialpremises',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videocommercialpremises',
            name='add_text',
            field=models.CharField(blank=True, default='text', max_length=300, verbose_name='Доплнительный текст'),
            preserve_default=False,
        ),
    ]
