# Generated by Django 3.0.6 on 2020-05-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0008_auto_20200511_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialpremises',
            name='ready_commercial_premise',
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='building_commercial_premise',
            field=models.BooleanField(default=False, help_text='Находиться в процессе строительства.', verbose_name='Строящее'),
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='finished_commercial_premise',
            field=models.BooleanField(default=False, help_text='Построенное помещение.', verbose_name='Готовое'),
        ),
    ]
