# Generated by Django 3.0.6 on 2020-05-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0009_auto_20200517_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialpremises',
            old_name='rent_price',
            new_name='rent_price_month',
        ),
        migrations.AddField(
            model_name='commercialpremises',
            name='rent_price_sq_m',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоимость аренды, руб/кв.м.'),
        ),
    ]
