# Generated by Django 3.0.6 on 2020-05-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0010_auto_20200517_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialpremises',
            name='cost_of_sale',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Стоймость на продажу'),
        ),
    ]
