# Generated by Django 3.0.6 on 2020-05-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_properties', '0011_commercialpremises_cost_of_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialpremises',
            name='comment_kw',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к "кВт"'),
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='max_average_rental_rate',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Средняя арендная ставка до, руб/кв.м.'),
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='min_average_rental_rate',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Средняя арендная ставка от, руб/кв.м.'),
        ),
        migrations.AlterField(
            model_name='commercialpremises',
            name='possible_income',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Возможный доход, руб/мес.'),
        ),
    ]
