# Generated by Django 3.0.6 on 2020-05-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0008_auto_20200518_1843'),
        ('commercial_properties', '0015_auto_20200518_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialpremises',
            name='address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compremises_address', to='geo_location.Address', verbose_name='Адрес'),
        ),
    ]
