# Generated by Django 3.0.6 on 2020-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='alt_attr',
            field=models.CharField(blank=True, default='text', max_length=300, verbose_name='img alt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='alt_attr',
            field=models.CharField(blank=True, default='text', max_length=300, verbose_name='img alt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='district',
            name='subname',
            field=models.CharField(max_length=10, unique=True, verbose_name='Сокращённое название'),
        ),
        migrations.AlterField(
            model_name='region',
            name='alt_attr',
            field=models.CharField(blank=True, default='text', max_length=300, verbose_name='img alt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, default='text', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
