# Generated by Django 3.0.6 on 2020-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0002_auto_20200511_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetNumHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Улица')),
                ('num_house', models.CharField(blank=True, max_length=150, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Улица и номер дома',
                'verbose_name_plural': 'Улицы и номера домов',
                'ordering': ['name'],
            },
        ),
    ]
