# Generated by Django 3.0.6 on 2020-05-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0003_streetnumhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Номер дома / корпуса')),
            ],
            options={
                'verbose_name': 'Номер дома',
                'verbose_name_plural': 'Номера домов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Улица и номер дома',
                'verbose_name_plural': 'Улицы и номера домов',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='StreetNumHouse',
        ),
    ]
