# Generated by Django 3.0.6 on 2020-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_location', '0007_auto_20200518_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Адрес'),
        ),
    ]
